### ISSUE TITLE
AWS credentials expiring when using an Instance Profile for credentials

### ISSUE THREAD

**Issue by gilandose** [lensesio/secret-provider#11]
I'm using this connector and I notice when we boot up the kafka connect service the provider works fine, if after some time we refresh a connector and we need to retrieve a secret the token we get `ExpiredTokenException`

We're using InstanceProfiles to provide the credentials to the box, as this is considered best practice for providing credentials to the resource rather than using static credentials. This provides temporary credentials to the resource that should be refreshed.

`Caused by: com.amazonaws.services.secretsmanager.model.AWSSecretsManagerException: The security token included in the request is expired (Service: AWSSecretsManager; Status Code: 400; Error Code: ExpiredTokenException;`

Looking at the code https://github.com/lensesio/secret-provider/blob/60614f8866e8a0f9a712746703816375e6953d98/src/main/scala/io/lenses/connect/secrets/providers/AWSHelper.scala#L42  The StaticCredentialProvider is used, this means it will not check again for new credentials. I think the preferred option here is to actually pass `new DefaultAWSCredentialsProviderChain()`

```scala
    val credentialProvider = settings.authMode match {
      case AuthMode.CREDENTIALS =>
        new AWSStaticCredentialsProvider(new BasicAWSCredentials(settings.accessKey, settings.secretKey.value()))
      case _ =>
        new DefaultAWSCredentialsProviderChain()
    }
    AWSSecretsManagerClientBuilder
      .standard()
      .withCredentials(credentialsProvider)
      .withRegion(settings.region)
      .build()
```

**Comment by BhuviTheDataGuy** [comment]
Having similar issue (https://github.com/lensesio/secret-provider/issues/28) 
Any recommendation?
