### ISSUE TITLE
Use AWS IAM role - EC2

### ISSUE THREAD

**Issue by BhuviTheDataGuy** [lensesio/secret-provider#28]
There is a security concern while passing these 2 parameters in the worker.

```sh
config.providers.aws.param.aws.access.key=your-client-key
config.providers.aws.param.aws.secret.key=your-secret-key
```

Im going to deploy this plugin into an EC2 instance that already has an IAM role attached with Secret manager permission. Can I leverage that option instead of passing the keys in the worker properties?

**Comment by BhuviTheDataGuy** [comment]
Never mind, Solved it

**Comment by ashemachandan** [comment]
How did you fix this issue?
