### ISSUE TITLE
AWS Secret names with slash '/'

### ISSUE THREAD

**Issue by BhuviTheDataGuy** [lensesio/secret-provider#29]
I have a secret in AWS Secret manager with this name `dev/debezium/mysql/testservice/password`

I tried to use this name in my source connector.

```
 "database.password": "${aws:dev/debezium/mysql/testservice/password:mysql_pass}",
```

In my worker properties, the `file.dir=/etc/kafka`

And the error I got is,
```
java.nio.file.AccessDeniedException: /etc/kafka/dev
````

But when I created empty folders in the same SECRET NAME, then its resolved.

```
mkdir -p /etc/kafka/dev/debezium/mysql/testservice/password
```

**Comment by xphir** [comment]
I know the fact it makes an internal file and doesn't let you disable this functionality is an issue, the following is a workaround.

But for others having the same issue, the workaround is to make sure your specified `file.dir` in the config provider has the correct permissions. For example if you gave the following `config.providers.aws.param.file.dir=/connector-files/aws` then make sure you have the permission to write within the `/connector-files/aws` directory.

As long as you have the correct permissions within that folder you have specified, then it will create the full path in the background and it wont produce an error.

**Comment by davidsloan** [comment]
#19 (no longer storing secret files by path) and #50 (toggling on/off storing secrets using `file.write` property) should resolve this problem.  Both will be included in the next release.

**Comment by davidsloan** [comment]
This is released in [https://github.com/lensesio/secret-provider/releases/tag/2.3.0](2.3.0)
