### ISSUE TITLE
Hashicorp VaultProvider config option to override secret's lease duration.

### ISSUE THREAD

**Issue by Chrisss93** [lensesio/secret-provider#4]
If VaultProvider is used to seek secrets from a KV v2 secret engine in Hashicorp Vault, the lease_duration is often set to 0 since it doesn't seem possible to [set lease_durations on kv/v2 secrets](https://github.com/hashicorp/vault/issues/6274) nor does it respect Vault's default system TTL. This means the expiry-time is always clock-time and the cache is effectively useless.

To overcome this, secret-provider could add configurable Long to the `VaultSetting`: `overrideLeaseDuration` which `VaultProvider` will use in place of `getLeaseDuration` from Vault's `LogicalResponse`.

If there is interest here I can submit a PR.

**Comment by andrewstevenson** [comment]
@Chrisss93 contributions welcome!

**Comment by davidsloan** [comment]
@Chrisss93 as of v2.2.0 we now have default TTLs for Vault by setting the property `secret.default.ttl`

Does this resolve your issue?

**Comment by davidsloan** [comment]
I believe this is resolved as above.
