### ISSUE TITLE
Version 2.1.5 and 2.1.6 missing from Maven Central

### ISSUE THREAD

**Issue by tginsberg** [lensesio/secret-provider#41]
Is there any chance you could publish 2.1.6 and 2.1.5 to Maven Central? They appear to be missing and the latest it seems to have is 2.1.4.

Link: https://search.maven.org/artifact/io.lenses/secret-provider

**Comment by andrewstevenson** [comment]
@tginsberg We no longer publish to maven. Is there are reason you require it?

**Comment by tginsberg** [comment]
@andrewstevenson No, not any longer. We worked around it.
