### ISSUE TITLE
Support for custom K8s authentication path

### ISSUE THREAD

**Issue by dttung2905** [lensesio/secret-provider#46]
Hi team,

It's really really fantastic to see this project being active again. 

## Goal
We would like to support custom Authentication path for Vault K8s authentication, rather than the default one `v1/auth/kubernetes/login` as specified in [official doc](https://developer.hashicorp.com/vault/api-docs/auth/kubernetes#login) 

## Problem
- The current way is relying on the default value when calling `loginByKubernetes()` method
https://github.com/lensesio/secret-provider/blob/75238234be77a62938a339652d10c840089d3b97/secret-provider/src/main/scala/io/lenses/connect/secrets/providers/VaultHelper.scala#L81-L87

  where the path is hardcoded to ([source](https://github.com/jopenlibs/vault-java-driver/blob/f32c8ba5acf4bbcfe12e23387305685109444d68/src/main/java/io/github/jopenlibs/vault/api/Auth.java#L995))
```
    public AuthResponse loginByJwt(final String provider, final String role, final String jwt)
            throws VaultException {
        return retry(attempt -> {
            // HTTP request to Vault
            final String requestJson = Json.object().add("role", role).add("jwt", jwt)
                    .toString();
            final RestResponse restResponse = new Rest()
                    .url(config.getAddress() + "/v1/auth/" + provider + "/login")
```
- However the repo `vault-java-driver` has not been maintaiend in a few years with the reply from the original author ([link](https://github.com/BetterCloud/vault-java-driver/pull/245#issuecomment-954066376))

## My proposed solution

- For the secret-provider side, I did a rough sketch a while ago https://github.com/dttung2905/secret-provider/pull/1. Of course there are a few things to take care as well. For example, how to fallback when user does not provide any authentication path
- For `vault-java-driver`, the author has mentioned a few approaches in his post. I think the least disruptive would be switching to a community fork https://github.com/jopenlibs/vault-java-driver, which was very actively developed. I could submit another PR to add that feature on their side as well.

Please let me know what you think @davidsloan. Sorry for directly tagging you as your recent activity in this repo is the only reason that motivate me to write this lengthy issue :smile:

**Comment by davidsloan** [comment]
Hi @dttung2905 .  We at Lenses are happy to be back working on our open source projects!

Thanks for the detailed write-up of the issue.

The reliance the unmaintained vault lib is indeed an issue and we are looking into ways of addressing this.  Switching to the new fork is definitely an option we are evaluating, and as you say the least disruptive.

Please feel free to submit a PR to address your needs 🥇 .  Let me know if you need any support.  Thank you!

**Comment by dttung2905** [comment]
Hi @davidsloan,

Thanks so much for the support !. Let me find some time submit the changes on the fork of the Vault library first https://github.com/jopenlibs/vault-java-driver first, before making another changes on this repo :pray:
