### ISSUE TITLE
Azure secret provider throws exception with default secret file-enconding tag

### ISSUE THREAD

**Issue by Nardu92** [lensesio/secret-provider#54]
Hi,
I'm using version 2.1.6 of the secret provider plugin to access Azure keyvault secrets from a Kafka connector.
When updating the configuration of the connector I receive an error ( "No value found for 'UTF-8'") when retrieving the secret if my Azure keyvault secret has the default "file-enconding" tag with value "utf-8".

The issue does not appear if the tag is not present or if I change the value of the tag to "UTF8".

The tag "file-enconding" with value "utf-8" is added automatically if the secret is created with az cli and cannot be removed as described in [this issue](https://github.com/Azure/azure-cli/issues/6613)

Ideally the secret provider should be able to use the default value of the tag created by az cli.

Thanks

**Comment by davidsloan** [comment]
This is released in [2.3.0](https://github.com/lensesio/secret-provider/releases/tag/2.3.0)
