### ISSUE TITLE
Environment Secrets file.dir worker property in documentation

### ISSUE THREAD

**Issue by joshuagrisham-karolinska** [lensesio/secret-provider#55]
Hello!
Here is hopefully a minor one..

I see in the docs (for example: https://docs.lenses.io/5.2/connectors/connect-secrets/env/) it has always seemed to refer to `config.providers.env.file.dir` for the `file.dir` property of the Environment config provider.

If I configure my worker in this way, when I look in the Connect server log after the Environment config provider has been loaded, the `file.dir` property has a no value (it is blank).

If I instead configure my worker with `config.providers.env.param.file.dir` (note `.param.` after the provider name but before the parameter name) like you can see on other providers such as https://docs.lenses.io/5.2/connectors/connect-secrets/vault/, then I can see this `file.dir` property value show up in my Connect logs and it is no longer blank.

Either it is a mismatch in the docs or a mismatch in how Connect seems to be picking this up?

**Comment by davidsloan** [comment]
Hi @joshuagrisham-karolinska , thanks for reporting.  The flaw in our documentation has now been fixed.  Let us know if you spot anything else.
